# Generated by Django 3.1 on 2023-09-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='password123', max_length=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='username', max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
