# Generated by Django 4.0.1 on 2023-08-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_doctor_patient_receptionist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
