# Generated by Django 4.2.5 on 2023-09-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_doctor_password_alter_doctor_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
