# Generated by Django 4.0.1 on 2023-08-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_receptionist_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='profile_picture',
        ),
    ]
