# Generated by Django 4.2.5 on 2023-09-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
