# Generated by Django 4.0.1 on 2023-08-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_receptionist_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
