# Generated by Django 4.0.1 on 2023-08-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_receptionist_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile_picture',
        ),
    ]
