# Generated by Django 4.0.1 on 2023-09-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_doctor_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('drug', models.CharField(blank=True, max_length=100, null=True)),
                ('healthCondition', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.IntegerField(blank=True, max_length=4, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('pregnancy', models.BooleanField(blank=True, null=True)),
                ('name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
