# Generated by Django 4.0.1 on 2023-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_remove_patient_contact_number_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
