# Generated by Django 4.0.1 on 2023-09-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='name',
            new_name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='MRN',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
