# Generated by Django 4.0.1 on 2023-09-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
