# Generated by Django 4.0.1 on 2023-09-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_remove_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
