# Generated by Django 4.2.5 on 2023-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_alter_doctor_id_alter_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
